version: '3.8'
services:
  comqtt:
    build:
      context: comqtt/
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "1882:1882" 
      - "8080:8080"
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_USER: gotest
      MYSQL_PASSWORD: gotest
      MYSQL_ROOT_PASSWORD: gotest
      MYSQL_DATABASE: db
    volumes:
      - ../../../../_local_mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: docker/be/Dockerfile
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
     - ../../../../.:/go
  