version: '3.8'
services:
  comqtt:
    build:
      context: comqtt/
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "1882:1882"
      - "8080:8080"
  db:
    image: mysql:8.0
    ulimits:
      nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
        soft: 64000
        hard: 64000
    environment: &db_env
      MYSQL_USER: gotest
      MYSQL_PASSWORD: gotest
      MYSQL_ROOT_PASSWORD: gotest
      MYSQL_DATABASE: db
    volumes:
      - db:/var/lib/mysql
  web:
    image: golang:1.23.0
    working_dir: /app
    volumes:
      - .:/app
    environment:
      <<: *db_env
    ports:
      - "3000:3000"
    entrypoint: ["sh", "-c", "go install github.com/air-verse/air@latest && sleep 5 && air"]
    links:
      - db
      - comqtt
volumes:
  db:
    driver: local
networks:
  shared: